#Creating Docker registry secret to store docker hub credentials
apiVersion: v1
kind: Secret
metadata:
  name: docker-secret
data:
  .dockerconfigjson: dockerfilebase64encode
type: kubernetes.io/dockerconfigjson