kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csye7374-project-operator
subjects:
- kind: ServiceAccount
  name: csye7374-project-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: csye7374-project-operator
  apiGroup: rbac.authorization.k8s.io
